### ISSUE TITLE
在TypeScript怎么用taobao 的SDK

### ISSUE THREAD

**Issue by gnu4cn** [zsqk/taobao-sdk#3]
官方的sdk是nodejs的，也没发布typescript的。

**Comment by iugo** [comment]
这个只是一个封装, 是用 TypeScript 写的.

淘宝开放平台的 API 都是基于 HTTP 的, 本项目就是封装了 HTTP 请求, 加上了常用的如签名鉴权等功能.

之所以存在这个项目是因为官方的 SDK 依赖太多, 很臃肿.

**Comment by iugo** [comment]
无论使用的是 TypeScript 还是 JavaScript, 都可以使用本项目替代官方的 SDK.

方法:

1. 安装依赖, 如 `npm i @zsqk/taobao-sdk`.
2. 引入业务代码, 如

```
const { topRequest, genTaobaoTimestamp } = require("@zsqk/taobao-sdk");

await topRequest('taobao.jst.astrolabe.storeinventory.iteminitial', {
  session: '',
  stores: JSON.stringify([{
    warehouse_type:'STORE',
  }]),
  operation_time: genTaobaoTimestamp(),
});
```

**Comment by gnu4cn** [comment]
好的，谢谢
